export const FEE_MODULE_CODE_ID = process.env.NEXT_PUBLIC_FEE_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_FEE_MODULE_CODE_ID)
  : 0

export const MARKETPLACE_MODULE_CODE_ID = process.env
  .NEXT_PUBLIC_MARKETPLACE_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_MARKETPLACE_MODULE_CODE_ID)
  : 0

export const MERGE_MODULE_CODE_ID = process.env.NEXT_PUBLIC_MERGE_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_MERGE_MODULE_CODE_ID)
  : 0

export const METADATA_MODULE_CODE_ID = process.env
  .NEXT_PUBLIC_METADATA_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_METADATA_MODULE_CODE_ID)
  : 0

export const MINT_MODULE_CODE_ID = process.env.NEXT_PUBLIC_MINT_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_MINT_MODULE_CODE_ID)
  : 0

export const PERMISSION_MODULE_CODE_ID = process.env
  .NEXT_PUBLIC_PERMISSION_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_PERMISSION_MODULE_CODE_ID)
  : 0

export const TOKEN_MODULE_CODE_ID = process.env.NEXT_PUBLIC_TOKEN_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_TOKEN_MODULE_CODE_ID)
  : 0

export const WHITELIST_MODULE_CODE_ID = process.env
  .NEXT_PUBLIC_WHITELIST_MODULE_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_WHITELIST_MODULE_CODE_ID)
  : 0

export const ATTRIBUTE_PERMISSION_CODE_ID = process.env
  .NEXT_PUBLIC_ATTRIBUTE_PERMISSION_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_ATTRIBUTE_PERMISSION_CODE_ID)
  : 0

export const LINK_PERMISSION_CODE_ID = process.env
  .NEXT_PUBLIC_LINK_PERMISSION_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_LINK_PERMISSION_CODE_ID)
  : 0

export const OWNERSHIP_PERMISSION_CODE_ID = process.env
  .NEXT_PUBLIC_OWNERSHIP_PERMISSION_CODE_ID
  ? Number(process.env.NEXT_PUBLIC_OWNERSHIP_PERMISSION_CODE_ID)
  : 0
